### ISSUE TITLE
Maybe the `gold_span` is mixing with `pred_span` when evaluating in `pred_span` mode?

### ISSUE THREAD

**Issue by Spico197** [dolphin-zs/Doc2EDAG#19]
Hi, there. Thanks for your excellent work.

In the code [here](https://github.com/dolphin-zs/Doc2EDAG/blob/da4f4bc0b9a896170d7f220baf3fe85cb535a025/dee/dee_model.py#L43), you just use the gold span if there is no pred span. Considering the situation of evaluating and predicting, is there a risk leading an evaluation bias (since we still can get the right span predictions if there is no span prediction outputs)?

Thank you very much if you could comment and give more explanations.

**Comment by shun-zheng** [comment]
Well, you are right. It indeed has the risk of leaking gold spans, but such risk is nearly negligible when the model is well trained.

The code here is just a hot fix to avoid the training crash at an early stage. Once the model is well trained, the NER module can always produce some candidate spans, so the length of span_token_tup_list will be greater than zero and the model will not use those gold spans. According to our experience on the ChFinAnn dataset, a well-trained model always produces some candidate spans, so the forementioned risk is limited.

We appreciate your findings, it should be better if we disable that statement for evaluation to be risk-free.

**Comment by Spico197** [comment]
Very appreciate for your reply.
